import { ROUTES } from '@/shared/model/routes';

export const HIDDEN_PAGES: string[] = [
	ROUTES.PRIVATE.FAVORITES,
	ROUTES.PRIVATE.PLAYLISTS,
	ROUTES.PRIVATE.SINGLE_PLAYLIST,
	ROUTES.PRIVATE.SUBSCRIPTION,
];
